name: ScottCheck
version: 0.1.0
category: game

dependencies:
  - base
  - parsers
  - text
  - attoparsec
  - mtl
  - transformers
  - lens
  - monad-loops
  - containers
  - array
  - sbv
  - optparse-applicative

source-dirs:
  - src

ghc-options:
  -Wunused-imports -Wunused-binds
  
executables:
  scott-check:
    main: main.hs
