name: ScottCheck
version: 0.1.0
category: game

dependencies:
  - base
  - array
  - sbv

source-dirs:
  - src

ghc-options:
  -Wunused-imports -Wunused-binds
  
executables:
  scott-check:
    main: main.hs
