name: ScottCheck
version: 0.1.0
category: game
license: MIT

dependencies:
  - base
  - parsers
  - text
  - attoparsec
  - mtl
  - transformers
  - lens
  - containers
  - array
  - sbv
  - optparse-applicative

source-dirs:
  - src

executables:
  scott-check:
    main: main.hs
